"""Transactional setup using the pre-commit framework's own installer."""
from __future__ import annotations

import importlib.util
import shutil
import stat
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path

import yaml

from .core import AGENTS, HOOK_BEGIN, _git, save_configuration


# These are Git hook names supported by pre-commit, not arbitrary file paths.
HOOK_TYPES = (
    "pre-commit", "pre-merge-commit", "pre-push", "prepare-commit-msg",
    "commit-msg", "post-commit", "post-checkout", "post-merge", "post-rewrite", "pre-rebase",
)
CONFIG_KEYS = ("agent-session.agent", "agent-session.source")
DEFAULT_CONFIG = """minimum_pre_commit_version: "3.2.0"
default_install_hook_types: [pre-commit, post-commit]

repos:
  - repo: https://github.com/Gentle-Lijie/AgentLedger
    rev: v0.1.2
    hooks:
      - id: agent-session-commit
"""
PRE_COMMIT_MARKER = b"# File generated by pre-commit: https://pre-commit.com"
# pre-commit 3.2+ recognizes these IDs, not its human-readable comment, when
# deciding whether an existing hook can be replaced without moving it to .legacy.
PRE_COMMIT_SCRIPT_IDS = (
    b"138fd403232d2ddd5efb44317e38bf03",
    b"4d9958c90bc262f47553e2c073f14cfe", b"d8ee923c46731b42cd95cc869add4062",
    b"49fd668cb42069aa1b6048464be5d395", b"79f09a650522a87b0da915d0d983b2de",
    b"e358c9dae00eac5d06b38dfdb1e33a8c",
)
NATIVE_MARKERS = (HOOK_BEGIN.encode(), b"# >>> agentledger >>>")


def _detect_controller() -> tuple[str, ...]:
    if importlib.util.find_spec("pre_commit") is not None:
        return (sys.executable, "-m", "pre_commit")
    executable = shutil.which("pre-commit")
    if executable:
        return (executable,)
    raise RuntimeError(
        "pre-commit is not installed. Install the framework with "
        '`python -m pip install "agent-session-commit[pre-commit]"` '
        "or `python -m pip install pre-commit`, then run setup again."
    )


def _regular_file_or_missing(path: Path) -> None:
    # Reject links even when broken: an installer must not follow user files
    # outside the configured hook directory or edit a linked YAML file.
    if path.is_symlink() or (path.exists() and not path.is_file()):
        raise RuntimeError(f"Unsafe setup path (expected a regular file): {path}")


@dataclass(frozen=True)
class _FileSnapshot:
    contents: bytes | None
    mode: int | None

    @classmethod
    def capture(cls, path: Path) -> _FileSnapshot:
        _regular_file_or_missing(path)
        if not path.exists():
            return cls(None, None)
        return cls(path.read_bytes(), stat.S_IMODE(path.stat().st_mode))

    def restore(self, path: Path) -> None:
        # Do not follow a link left by a failed installer during rollback.
        if path.is_symlink():
            path.unlink()
        if path.exists() and not path.is_file():
            raise RuntimeError(f"Cannot restore hook over a non-file: {path}")
        if self.contents is None:
            path.unlink(missing_ok=True)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(self.contents)
            path.chmod(self.mode)


class PreCommitSetup:
    """Preflight before prompting; apply selected configuration with install().

    Existing YAML is validated and read without serialization. Only a missing
    config is generated, and pre-commit owns installation and legacy chaining.
    """

    def __init__(self, root: Path):
        root = Path(root).resolve()
        self.root = Path(_git(root, "rev-parse", "--show-toplevel").stdout.strip()).resolve()
        self.controller = _detect_controller()
        self.config_path = self.root / ".pre-commit-config.yaml"
        raw_hooks = Path(_git(self.root, "rev-parse", "--git-path", "hooks").stdout.strip())
        self.hooks_dir = raw_hooks if raw_hooks.is_absolute() else self.root / raw_hooks
        self._preflight()

    def _run_controller(self, *args: str) -> None:
        result = subprocess.run(
            [*self.controller, *args], cwd=self.root, capture_output=True, text=True,
            encoding="utf-8", errors="replace",
        )
        if result.returncode:
            detail = result.stderr.strip() or result.stdout.strip() or "no diagnostic output"
            raise RuntimeError(f"pre-commit {args[0]} failed: {detail}")

    def _hook_paths(self, hook_types: tuple[str, ...]) -> list[Path]:
        # Validate here too, so hook paths never accept traversal or CLI flags.
        if any(name not in HOOK_TYPES for name in hook_types):
            raise RuntimeError("Unsupported or unsafe Git hook type in pre-commit configuration.")
        return [self.hooks_dir / (name + suffix)
                for name in hook_types for suffix in ("", ".legacy")]

    def _read_config(self) -> tuple[str, ...]:
        _regular_file_or_missing(self.config_path)
        if not self.config_path.exists():
            return ("pre-commit", "post-commit")
        self._run_controller("validate-config", str(self.config_path))
        try:
            document = yaml.safe_load(self.config_path.read_bytes())
        except (yaml.YAMLError, UnicodeError) as exc:
            raise RuntimeError(f"Cannot parse {self.config_path.name}: {exc}") from exc
        if not isinstance(document, dict):
            raise RuntimeError("pre-commit configuration must be a YAML mapping.")
        repos = document.get("repos")
        if not isinstance(repos, list):
            raise RuntimeError("pre-commit configuration must contain a repos list.")
        found = False
        for repo in repos:
            if not isinstance(repo, dict) or not isinstance(repo.get("hooks"), list):
                raise RuntimeError("Each pre-commit repository must contain a hooks list.")
            for hook in repo["hooks"]:
                if not isinstance(hook, dict):
                    raise RuntimeError("Each pre-commit hook must be a mapping.")
                if hook.get("id") in ("agent-session-commit", "agentledger"):
                    if "stages" in hook and hook["stages"] != ["post-commit"]:
                        raise RuntimeError(
                            f"{hook['id']} must run only at post-commit to amend the just-created commit. "
                            "Remove the stages override or set stages: [post-commit]."
                        )
                    if hook.get("always_run") is False:
                        raise RuntimeError(
                            f"{hook['id']} requires always_run: true so the post-commit hook is not skipped. "
                            "Remove the always_run: false override or set always_run: true."
                        )
                    found = True
        if not found:
            raise RuntimeError(
                "Existing .pre-commit-config.yaml has no agent-session-commit hook "
                "(legacy agentledger is also accepted). Merge the hook from "
                "https://github.com/Gentle-Lijie/AgentLedger/blob/main/"
                "examples/.pre-commit-config.yaml into your config, then run setup again."
            )
        defaults = document.get("default_install_hook_types", ["pre-commit"])
        if not isinstance(defaults, list) or any(
            not isinstance(name, str) or name not in HOOK_TYPES for name in defaults
        ):
            raise RuntimeError("Unsupported or unsafe default_install_hook_types in pre-commit configuration.")
        return tuple(dict.fromkeys([*defaults, "post-commit"]))

    def _preflight(self) -> tuple[str, ...]:
        # No --local: git returns matching values from every active config scope,
        # including includes and command-line/environment configuration.
        hooks_path = _git(self.root, "config", "--get-all", "core.hooksPath", check=False)
        if hooks_path.returncode == 0:
            raise RuntimeError(
                "core.hooksPath is configured. Use "
                "`git config --show-origin --get-all core.hooksPath` to locate it "
                "and migrate/remove it in its defining scope before using pre-commit."
            )
        if hooks_path.returncode != 1:
            raise RuntimeError(hooks_path.stderr.strip() or "Cannot inspect core.hooksPath.")
        if self.hooks_dir.is_symlink() or (self.hooks_dir.exists() and not self.hooks_dir.is_dir()):
            raise RuntimeError(f"Unsafe hooks directory: {self.hooks_dir}")
        for name in HOOK_TYPES:
            path = self.hooks_dir / name
            _regular_file_or_missing(path)
            if path.exists() and any(marker in path.read_bytes() for marker in NATIVE_MARKERS):
                raise RuntimeError(
                    f"Native Agent Session Commit hook found at {path}. "
                    "Migrate by running `agent-session-commit uninstall` first, "
                    "then run pre-commit setup again."
                )
        hook_types = self._read_config()
        for path in self._hook_paths(hook_types):
            _regular_file_or_missing(path)
        for name in hook_types:
            active = self.hooks_dir / name
            legacy = self.hooks_dir / (name + ".legacy")
            if (active.exists() and legacy.exists()
                    and not any(identifier in active.read_bytes() for identifier in PRE_COMMIT_SCRIPT_IDS)):
                raise RuntimeError(
                    f"Both {active.name} and {legacy.name} contain existing hooks. "
                    "Merge/migrate them before setup so pre-commit cannot overwrite a legacy hook."
                )
        return hook_types

    def _local_values(self, key: str) -> list[str]:
        result = _git(self.root, "config", "--local", "--null", "--get-all", key, check=False)
        if result.returncode == 1:
            return []
        if result.returncode:
            raise RuntimeError(result.stderr.strip() or f"Cannot inspect local Git config {key}.")
        return result.stdout.removesuffix("\0").split("\0")

    def install(self, agent: str, source: Path) -> None:
        if agent not in AGENTS:
            raise RuntimeError(f"Unknown agent: {agent}")
        # Repeat preflight after the wizard to catch configuration changes.
        hook_types = self._preflight()
        old_values = {key: self._local_values(key) for key in CONFIG_KEYS}
        snapshots = {path: _FileSnapshot.capture(path) for path in self._hook_paths(hook_types)}
        hooks_dir_existed = self.hooks_dir.exists()
        created_config = False
        try:
            if not self.config_path.exists():
                # Exclusive creation also protects a config added during setup.
                with self.config_path.open("xb") as stream:
                    created_config = True
                    stream.write(DEFAULT_CONFIG.encode("utf-8"))
                self._run_controller("validate-config", str(self.config_path))
            save_configuration(self.root, agent, source)
            flags = [flag for name in hook_types for flag in ("--hook-type", name)]
            self._run_controller("install", "--install-hooks", *flags)
        except (Exception, KeyboardInterrupt) as exc:
            errors: list[str] = []
            for path, snapshot in snapshots.items():
                try:
                    snapshot.restore(path)
                except (OSError, RuntimeError) as restore_error:
                    errors.append(str(restore_error))
            for key, values in old_values.items():
                try:
                    unset = _git(self.root, "config", "--local", "--unset-all", key, check=False)
                    if unset.returncode not in (0, 5):
                        raise RuntimeError(unset.stderr.strip() or f"Cannot restore {key}.")
                    for value in values:
                        _git(self.root, "config", "--local", "--add", key, value)
                except (OSError, RuntimeError) as restore_error:
                    errors.append(str(restore_error))
            if created_config:
                try:
                    self.config_path.unlink(missing_ok=True)
                except OSError as restore_error:
                    errors.append(str(restore_error))
            if not hooks_dir_existed and self.hooks_dir.is_dir():
                try:
                    if not any(self.hooks_dir.iterdir()):
                        self.hooks_dir.rmdir()
                except OSError as restore_error:
                    errors.append(str(restore_error))
            suffix = f" Rollback also failed: {'; '.join(errors)}" if errors else " Setup changes were rolled back."
            raise RuntimeError(f"pre-commit setup failed: {exc}.{suffix}") from exc
